var region_radio_wrapper = document.getElementById("region-radio-wrapper"),
    product_radio_wrapper = document.getElementById("product-radio-wrapper"),
    region_checkbox_val = ["华东","华南","华北"],
    product_checkbox_val = ["手机","笔记本","智能音箱"],
    checked_count = {regionChecked:0,productChecked:0},
    checked_items = {regions:[],products:[]},
    tbWrapper = document.getElementById("table-wrapper"),
    thWrapper = document.getElementById("th-wrapper"),
    tby = tbWrapper.querySelector("tbody");